channels:
- conda-forge
dependencies:
- python=3.9.19
- pip<=24.0
- pip:
  - mlflow==2.15.1
  - cffi==1.16.0
  - cloudpickle==3.0.0
  - dask-expr==1.1.6
  - defusedxml==0.7.1
  - distributed==2024.6.2
  - graphviz==0.20.3
  - jinja2==3.1.4
  - matplotlib==3.7.5
  - numpy==1.26.1
  - pandas==2.1.4
  - pyarrow==15.0.2
  - pycaret==3.3.2
  - scikit-learn==1.4.2
  - scipy==1.11.3
name: mlflow-env
